### PR TITLE
Refactor to align with rprojroot and here

### LINKED ISSUE #17: add 'starting_dir' parameter
https://github.com/chendaniely/pyprojroot/blob/d7ddccd679ad35860ca76cbd795f1ed3be52efac/pyprojroot/pyprojroot.py#L44

There is a problem assuming `cwd` if this code gets used from outside the assumed project. It would be a user responsibility to provide something like `__file__` as a starting dir.

### LINKED ISSUE #18: Convergence with rprojroot
First, thanks for making this. It's been on my TODO list for a long time: https://github.com/jamesmyatt/pyprojroot

The interface of this library is very different from that used by rprojroot. Would it be OK to change it to be closer? In particular, the main function is `find_root` and it takes some `criterion` as the main input. What do you think?

### PR DESCRIPTION
**Pull request by jamesmyatt**
Major refactoring to allow the library to provide the same kind of functionality as both the rprojroot and here R libraries.

There's still lots of functionality in rprojroot and here that isn't implemented in this PR, but it's a start.

Closes #18, Closes #17

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@chendaniely , What do you think of this? Any chance of getting this merged?

**Comment by jamesmyatt** [comment]
@chendaniely , it's been over 6 weeks. Do you have any feedback?

**Comment by pashminacameron** [comment]
Hey @chendaniely, @jamesmyatt It will be good to get this fix merged. I am also seeing the `RecursionError` issue and this pull request fixes it.

**Comment by jamesmyatt** [comment]
@chendaniely , ping

**Comment by jamesmyatt** [comment]
@chendaniely , Can I get some feedback on this? It's been nearly _6 months_. Or is the project dead? I know there are conflicts to resolve, but I won't bother if there's no chance of getting it merged.

**Comment by pashminacameron** [comment]
I created [py-repo-root](https://github.com/pashminacameron/py-repo-root/) with most of the fixes I could think of.

**Comment by chendaniely** [comment]
hey @jamesmyatt appologies about the really delayed reponse.

Thanks for the refactor (and bumping the version number). I should be able to getting around with the merge conflicts this week and then i'll merge this in!

**Comment by chendaniely** [comment]
alright, the conflicts have been fixed!
Just need to update the `setup.py` so it doesn't break any code that does `from pyprojroot import here` since it currently needs to be written as `from pyprojroot.here import here`

**Comment by chendaniely** [comment]
closes #16

**Pull request merged**
