### PR TITLE
consolidate dev

### PR DESCRIPTION
**Pull request by achimgaedke**
@chendaniely - that should be a "one click stop" for getting the `dev` branch up to specs...

It contains the now updated `fix_mypy_strict`branch + 4 commits of today:

* fixup formatting
* carry over from #32 comments - fixing the "else" to prevent silent fails
* replace `setup.py` with `setup.cfg` & `pyproject.toml`
* introduce a "legacy" module

To help with reviewing: here is the "diff" of the 4 commits: https://github.com/chendaniely/pyprojroot/compare/4b6ffd1...2403bc3

Legacy module `pyprojroot.pyprojroot`: When researching the existing use of this package (advanced search on github), I found several projects doing a:

```python3
import pyprojroot.pyprojroot
```

So I've re-implemented that with backwards-compatible functions.

That's roughly all from my side for a 0.3.0 release.

### CODE REVIEW

**Comment by achimgaedke** [comment]
Thinking about the legacy function fix. Maybe the `pyprojroot.here` should also be able to take  3 arguments as before.

**Comment by chendaniely** [comment]
I like where this is going and what you mentioned from the multiple use cases in [this comment](https://github.com/chendaniely/pyprojroot/issues/33#issuecomment-1437987407) of how people might use the package.

I did a quick PyPI search for "here" and "pyhere" becuase the R community technically also refactored `here()` into its own function + package. I found this package: https://pypi.org/project/pyhere/

so maybe retaining the orginal functionality of `pyprojroot.here()` isn't as important. But I do think most people would just rush to only use the `here()` function. so maybe that's just something we put in the `__init__.py` file so it's easily importable + useable? I think that's what you did by moving the `pyprojroot.pyprojroot.here` to `pyprojroot.here.here`?

---

> Thinking about the legacy function fix. Maybe the pyprojroot.here should also be able to take 3 arguments as before.

I think you're refering to the fact you removed `param project_files: list of files to track inside the project`? I deviated from R's implementation by passing defualt arguments into that parameter becuase this is a "new" package in the Python world. I wanted a way for people to specify _any_ file they may need as the "root" starting point. It was also to account for the fact that there are _so many_ tools people use for interacting with python, I wanted to try to capture the big ones (git, vscode, pycharm) and give the flexibilty for people to specify whatever else they need. Otherwise we'd all be in an enless "can this support .... file/directories"?

R does a lot of these package config things via options. I've used a few `.option` things in Pandas as well. Maybe that's how we can store all the list of files + folders so people can modify them at the top of scripts (or even their own enviornment)?
https://github.com/chendaniely/pyprojroot/blob/2403bc312b06fdcf804ceda0eae9d76b17f1bd10/src/pyprojroot/here.py#L16

---

Also since you added a deprecation warning to `pyprojroot.pyprojroot.here()` we should mention they should look into an use `pyprojroot.here.here()`, right? Just making sure i'm reading the old + new stuff correctly.

**Comment by achimgaedke** [comment]
Hey Daniel!

I'm talking here from my "short term view" perspective.

* I'm acting at the moment more as a facilitator to get the existing dev code over the line.
* I actually did not do anything substantial coding wise here, it is based on what was done 1.5 years ago.
* I actually synced up the doc with the parameters in the code, I didn't remove the `project_files` parameter
* Advocating for the existing user base: Version 0.3 should be as backwards compatible to 0.2 as possible

Could we please merge this branch into dev and work from there? One place/branch less to look at...

**Comment by achimgaedke** [comment]
As a contrast to the agenda above: Just want to mention where I would like to head, but probably discuss this in another issue.

* get an idea about a pythonic version of the XXX-projroot workflow and make this available at `pyprojroot`
* implement other workflows as pyprojroot.here or pyprojroot.rprojroot or so...
* have one solid core code base serving all 3 workflows

Once we got an 0.3 out we can make a plan what to take from there for this project.
That's roughly what I investigated as a spike solution at https://github.com/achimgaedke/pyprojroot2 ... and

**Comment by achimgaedke** [comment]
And yes, I totally agree

> t was also to account for the fact that there are so many tools people use for interacting with python, I wanted to try to capture the big ones (git, vscode, pycharm) and give the flexibilty for people to specify whatever else they need. Otherwise we'd all be in an enless "can this support .... file/directories"?

But that wasn't my agenda t remove it in first palce.

**Comment by chendaniely** [comment]
Thanks @achimgaedke : all good points. i'll get this all merged in and we can start off a better place for v0.3.0
I'm going to gather a few thoughts into a separate thread so we can plan overall direction + features.

Hopefully, we can leave the minor improvement stuff for the conference sprint happening in 2 weeks.

**Comment by achimgaedke** [comment]
@chendaniely, is there anything one could help with?

**Pull request merged**
